<div>
    <label>
        Имя *
        <br>
        <input type="text" name="post[name]" value="<?= htmlspecialchars($postData['name'] ?? '') ?>">
    </label>
    <?php if (isset($errors['name'])): ?>
        <div><?= $errors['name'] ?></div>
    <?php endif ?>
</div>
<div>
    <label>
        Содержимое *
    </label>
    <br>
    <textarea type="text" rows="5" cols="20" name="post[body]"><?= htmlspecialchars($postData['body'] ?? '') ?></textarea>
    <?php if (isset($errors['body'])): ?>
        <div><?= $errors['body'] ?></div>
    <?php endif ?>
</div>