<a href="/users">Назад к списку пользователей</a>

<table>
    <tr>
        <td>
            <p>Id</p>
        </td>
        <td>
            <?= $id ?>
        </td>
    </tr>
    <tr>
        <td>
            <p>First Name</p>
        </td>
        <td>
            <?= $user['firstName'] ?>
        </td>
    </tr>
    <tr>
        <td>
            <p>Last Name</p>
        </td>
        <td>
            <?= $user['lastName'] ?>
        </td>
    </tr>
    <tr>
        <td>
            <p>Email</p>
        </td>
        <td>
            <?= $user['email'] ?>
        </td>
    </tr>
</table>