<?php



function getLinks($tags)
{
    $mapping = [
        'a' => 'href',
        'img' => 'src',
        'link' => 'href'
    ];

    $filteredTags = array_filter($tags, function ($tag) use ($mapping) {
        return in_array($tag['name'], array_keys($mapping));
    });

    $paths = array_map(function ($tag) use ($mapping) {
        $attributeName = $mapping[$tag['name']];
        return $tag[$attributeName];
    }, $filteredTags);
    return array_values($paths);
}


$tags = [
    ['name' => 'img', 'src' => 'hexlet.io/assets/logo.png'],
    ['name' => 'div'],
    ['name' => 'link', 'href' => 'hexlet.io/assets/style.css'],
    ['name' => 'h1']
];
$links = getLinks($tags);
