<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

    <a href="/posts/new">Новый пост</a>

<?php foreach ($posts as $post): ?>
    <div>
        <?= htmlspecialchars($post['name']) ?>
    </div>
<?php endforeach ?>