<form action="/schools/<?= htmlspecialchars($school['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
        <label>
            Название *
            <input type="text" name="school[name]" value="<?= htmlspecialchars($school['name'] ?? ''); ?>">
        </label>
        <?php if (isset($errors['name'])): ?>
            <div><?= $errors['name'] ?></div>
        <?php endif ?>
    </div>
    <input type="submit" value="Update">
</form>